# Generated by Django 4.2.10 on 2024-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_garbageinfo_manager_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbageinfo',
            old_name='image_garbage',
            new_name='image_garbage_predict',
        ),
        migrations.RenameField(
            model_name='garbageinfo',
            old_name='type_garbage',
            new_name='type_garbage_predict',
        ),
        migrations.AddField(
            model_name='garbageinfo',
            name='predict_precent',
            field=models.FloatField(default=0.0),
        ),
    ]
