# Generated by Django 4.2.10 on 2024-04-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_address_alter_profile_phone_garbage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garbage',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='GarbageCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_compartment', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garbage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garbage_w_GarbageCompartment', to='api.garbage')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
