# Generated by Django 4.2.10 on 2024-04-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_garbage_options_garbagecompartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_garbage', models.CharField(blank=True, max_length=50, null=True)),
                ('image_garbage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('predict_precent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garbage_compartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garbage_compartment_w_predict_info', to='api.garbagecompartment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
