# Generated by Django 4.2.10 on 2024-05-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_name_compartment_garbagecompartment_type_name_compartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictinfo',
            old_name='predict_precent',
            new_name='predict_percent',
        ),
    ]
