# Generated by Django 4.2.10 on 2024-06-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'ordering': ('id',)},
        ),
    ]
